import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import{deltaToDraft,emptyDelta,isEditableSignedInteger,normalizeSignedInteger,parseDeltaDraft,projectStanding,validateAdjustment,type AdminStanding}from"../src/lib/admin/standings";
const row:AdminStanding={competitionSeasonId:"m",teamId:"t",teamName:"Test",kitColour:"#fff",position:1,played:10,wins:6,draws:2,losses:2,goalsFor:30,goalsAgainst:20,goalDifference:10,points:20};
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import StandingsManager from "../src/app/admin/standings/StandingsManager";

test("standing management exposes every division and explains empty data", () => {
 const editions = ["A", "B"].map(division => ({id:division,night:"monday" as const,division,label:division,season:"Audit"}));
 const html=renderToStaticMarkup(createElement(StandingsManager,{workspace:{editions,standings:[{...row,competitionSeasonId:"A"}],adjustments:[]},onChanged:async()=>{}}));
 assert.match(html, /<option value="A" selected="">A<\/option><option value="B">B<\/option>/);
 const empty=renderToStaticMarkup(createElement(StandingsManager,{workspace:{editions:[],standings:[],adjustments:[]},onChanged:async()=>{}}));
 assert.match(empty,/No standings are available for this competition\./);
 assert.doesNotMatch(html,/Snapshot automation remains inactive/);
});
test("standing projections apply positive and negative signed deltas",()=>{const d={...emptyDelta(),wins:1,losses:-1,goalsFor:2,goalsAgainst:-3,points:3};assert.deepEqual(projectStanding(row,d),{...row,wins:7,losses:1,goalsFor:32,goalsAgainst:17,goalDifference:15,points:23})});
test("adjustments require a reason and one non-zero whole value",()=>{assert.equal(validateAdjustment(emptyDelta(),"").length,2);assert.deepEqual(validateAdjustment({...emptyDelta(),points:-1},"Disciplinary deduction"),[]);assert.match(validateAdjustment({...emptyDelta(),points:1.5},"Reason")[0],/whole numbers/)});
test("standings route is static browser-side and reconfirms admin before mutation",()=>{const page=readFileSync("src/app/admin/standings/page.tsx","utf8"),action=readFileSync("src/lib/admin/standings-actions.ts","utf8"),data=readFileSync("src/lib/admin/standings-data.ts","utf8");assert.match(page,/AdminAuthGuard/);assert.match(action,/getUser\(\)/);assert.match(action,/rpc\("is_fis_admin"\)/);assert.match(data,/from\("standings"\)/);assert.match(data,/eq\("lifecycle","active"\)/);assert.doesNotMatch(`${page}${action}${data}`,/use server|service_role|SUPABASE_SERVICE/)});
test("publication uses the lifecycle RPC and snapshot input remains published-only",()=>{const action=readFileSync("src/lib/admin/standings-actions.ts","utf8"),snapshot=readFileSync("src/lib/public-competition.ts","utf8");assert.match(action,/rpc\("transition_standing_adjustment"/);assert.match(snapshot,/publication_state[\s\S]*published|eq\("publication_state", "published"\)/)});
test("transactional migration enforces lifecycle, immutability, follow-ups and stale versions",()=>{const sql=readFileSync("supabase/migrations/202609290001_transactional_standing_adjustments.sql","utf8");assert.match(sql,/pending_review/);assert.match(sql,/protect_published_standing_adjustment/);assert.match(sql,/standing_adjustments_one_followup/);assert.match(sql,/errcode='40001'/);assert.match(sql,/security definer set search_path=''/g);assert.doesNotMatch(sql,/on conflict\s*\(\s*(id|team_id|version)\s*\)/i)});
test("disposable adjustment verification is guarded, isolated and rollback-only",()=>{const verify=readFileSync("supabase/verification/verify_standing_adjustments.sql","utf8"),cleanup=readFileSync("supabase/tests/standing_adjustment_concurrency_cleanup.sql","utf8");assert.match(verify,/fis_fixture_test\.assert_disposable/);assert.match(verify,/00000000-0000-4000-8000-00000000d901/);assert.match(verify,/rollback;\s*$/);assert.match(cleanup,/administrator_preserved/);assert.match(cleanup,/marker_preserved/)});
test("standings presentation uses a semantic table and explicit adjustment actions",()=>{const manager=readFileSync("src/app/admin/standings/StandingsManager.tsx","utf8");assert.match(manager,/<table><thead><tr><th>POS<\/th><th>TEAM<\/th>/);assert.match(manager,/>Adjust<\/button>/);assert.match(manager,/className=\{selected\?\.teamId===r\.teamId\?"selected":""\}/);assert.match(manager,/Adjustment history/)});
test("mobile standings editor uses the accessible sheet interaction pattern",()=>{const manager=readFileSync("src/app/admin/standings/StandingsManager.tsx","utf8"),styles=readFileSync("src/app/globals.css","utf8");assert.match(manager,/role=\{phone\?"dialog":undefined\}/);assert.match(manager,/fisStandingSheet/);assert.match(manager,/event\.key==="Escape"/);assert.match(manager,/document\.body\.style\.overflow="hidden"/);assert.match(styles,/\.admin-standing-sheet \{[^}]*height: 100dvh[^}]*scroll-padding-bottom: calc\(40px \+ env\(safe-area-inset-bottom\)\)/);assert.match(styles,/\.admin-standing-sheet \.admin-team-actions \{[^}]*position: static[^}]*box-shadow: none/)});

test("standings workspace and table use the full available width",()=>{const styles=readFileSync("src/app/globals.css","utf8");assert.match(styles,/\.admin-workspace \{[^}]*width: 100%[^}]*min-width: 0/);assert.match(styles,/\.admin-standings-layout \{[^}]*grid-template-columns: minmax\(0,1fr\)[^}]*width: 100%/);assert.match(styles,/\.admin-standing-table \{[^}]*width: 100%[^}]*overflow-x: auto/)});

test("standing delta inputs are centred controlled signed-integer fields",()=>{const manager=readFileSync("src/app/admin/standings/StandingsManager.tsx","utf8"),styles=readFileSync("src/app/globals.css","utf8");assert.match(manager,/type="text" inputMode="text" pattern="-\?\[0-9\]\*"/);assert.match(manager,/value=\{deltaDraft\[key\]\}/);assert.match(manager,/onFocus=\{e=>e\.currentTarget\.select\(\)\}/);assert.match(manager,/onClick=\{e=>e\.currentTarget\.select\(\)\}/);assert.doesNotMatch(manager,/<small>\{delta/);assert.match(styles,/\.admin-delta-grid \{[^}]*repeat\(7,minmax\(0,1fr\)\)/);assert.match(styles,/\.admin-delta-grid input \{[^}]*height: 42px[^}]*text-align: center/)});

test("signed integer drafts preserve typing states and normalize completed values",()=>{assert.equal(isEditableSignedInteger(""),true);assert.equal(isEditableSignedInteger("-"),true);assert.equal(isEditableSignedInteger("-3"),true);assert.equal(isEditableSignedInteger("2"),true);assert.equal(isEditableSignedInteger("1.5"),false);assert.equal(normalizeSignedInteger("02"),"2");assert.equal(normalizeSignedInteger("-03"),"-3");assert.equal(normalizeSignedInteger("000"),"0");assert.equal(normalizeSignedInteger("-0"),"0");assert.equal(normalizeSignedInteger("-"),null);assert.equal(normalizeSignedInteger(""),null);assert.equal(normalizeSignedInteger("1.5"),null)});

test("incomplete signed integer drafts cannot become a submitted delta",()=>{const draft=deltaToDraft(emptyDelta());draft.points="-";assert.equal(parseDeltaDraft(draft),null);draft.points="";assert.equal(parseDeltaDraft(draft),null);draft.points="-3";assert.equal(parseDeltaDraft(draft)?.points,-3)});

test("mobile standing editor reserves an opaque sticky header for its close button",()=>{const styles=readFileSync("src/app/globals.css","utf8");assert.match(styles,/\.admin-standing-editor-header \{[^}]*grid-template-columns: minmax\(0,1fr\) 42px/);assert.match(styles,/\.admin-standing-sheet \.admin-standing-editor-header \{[^}]*position: sticky[^}]*min-height:[^}]*background: var\(--fis-cream-light\)/);assert.match(styles,/\.admin-standing-editor-header \.admin-panel-close \{[^}]*position: static[^}]*grid-column: 2[^}]*42px/)});
