import PolicyPage from "@/components/PolicyPage";

export const metadata = { title: "Terms & Conditions", description: "Participation and website terms for Futsal Indoor Soccer." };
const sections = [
  { heading: "Joining and eligibility", paragraphs: ["FIS competitions are for participants aged 18 and over. A registration is an enquiry and does not confirm a competition place. Team captains provide an initial roster and must ensure their players understand these Terms and the FIS Rules."] },
  { heading: "Competition participation", paragraphs: ["Participants agree to follow published fixtures, competition rules and reasonable directions from referees, FIS administrators and venue staff. Fixtures, times, courts, opponents and results may be corrected or changed; teams should check the current published information before travelling."] },
  { heading: "Code of conduct", paragraphs: ["Treat players, referees, organisers and venue staff with respect. Abusive, threatening, discriminatory or violent behaviour is not permitted. FIS may remove a participant from a match or competition after considering the circumstances."] },
  { heading: "Risk, fitness and medical treatment", paragraphs: ["Futsal involves physical exertion, contact and an inherent risk of injury. Each participant is responsible for assessing their fitness to play. Where a participant cannot provide instructions in an emergency, they authorise reasonable emergency medical assistance to be sought on their behalf."] },
  { heading: "Insurance and costs", paragraphs: ["FIS does not provide player personal accident or injury insurance. Players should consider private health or personal accident cover and remain responsible for ambulance, medical and related costs. Public liability cover is different from personal injury benefits and does not guarantee reimbursement of medical expenses.", "Nothing in these Terms excludes or limits rights or liability where doing so would be unlawful."] },
  { heading: "Photography and video", paragraphs: ["Photography and video may be captured during FIS competitions and used to document or promote the league. A player who does not consent should email FIS or identify themselves to FIS staff before their fixture so reasonable steps can be taken to respect that choice."] },
  { heading: "Privacy", paragraphs: ["Personal information is handled in accordance with the FIS Privacy Policy. By registering or participating, you acknowledge that policy and the publication of competition information such as team names, fixtures, results and tables."] },
  { heading: "Contact and changes", paragraphs: ["Email contact@futsalindoorsoccer.com.au with questions. Material updates to these Terms will include a revised date and may be communicated through normal FIS channels. Detailed legal wording remains subject to further review."] },
];
export default function TermsPage() { return <PolicyPage title="Terms & Conditions" updated="23 September 2026" sections={sections} />; }
