"use client";
import Link from "next/link";
import { useEffect,useMemo,useRef,useState,useTransition } from "react";
import { X } from "lucide-react";
import TeamKit from "@/components/TeamKit";
import { consequentialTeamChanges,filterAdminTeams,validateTeamDraft,type AdminTeam,type TeamDraft,type TeamPreference,type TeamStatus } from "@/lib/admin/teams";
import { saveTeamProfile } from "@/lib/admin/teams-actions";
import type { TeamsWorkspace } from "@/lib/admin/teams-data";

const presets=[{name:"White",value:"#FFFFFF"},{name:"Black",value:"#111111"},{name:"Blue",value:"#1E66E5"},{name:"Light blue",value:"#62C5E8"},{name:"Red",value:"#ED1C24"},{name:"Yellow",value:"#F2D34F"},{name:"Green",value:"#1F9D55"}];
const toDraft=(team:AdminTeam):TeamDraft=>({name:team.name,status:team.status,competitionSeasonId:team.competitionSeasonId,kitColour:team.kitColour??"",note:team.note,preferences:team.preferences.map(p=>({...p}))});

export default function TeamsManager({workspace,onChanged}:{workspace:TeamsWorkspace;onChanged():Promise<void>}){
 const initial=workspace.editions[0];const[night,setNight]=useState<"monday"|"wednesday">(initial?.night??"monday"),[division,setDivision]=useState(initial?.division??"A"),[search,setSearch]=useState(""),[status,setStatus]=useState<TeamStatus|"all">("all");
 const[selected,setSelected]=useState<AdminTeam|null>(null),[draft,setDraft]=useState<TeamDraft|null>(null),[reason,setReason]=useState(""),[notice,setNotice]=useState<{kind:"success"|"error";text:string}|null>(null),[phone,setPhone]=useState(false),[pending,startTransition]=useTransition();
 const panel=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement|null>(null);const divisions=[...new Set(workspace.editions.filter(e=>e.night===night).map(e=>e.division))].sort();const edition=workspace.editions.find(e=>e.night===night&&e.division===division)??workspace.editions.find(e=>e.night===night)??initial;
 const teams=useMemo(()=>edition?filterAdminTeams(workspace.teams,{editionId:edition.id,search,status}):[],[workspace.teams,edition,search,status]);const errors=selected&&draft?validateTeamDraft(selected,draft,reason):[];const consequences=selected&&draft?consequentialTeamChanges(selected,draft):[];
 useEffect(()=>{const query=matchMedia("(max-width: 620px)"),update=()=>setPhone(query.matches);update();query.addEventListener("change",update);return()=>query.removeEventListener("change",update)},[]);
 useEffect(()=>{if(!phone||!selected)return;const y=scrollY,background=[...document.querySelectorAll<HTMLElement>(".site-header,.site-footer,.admin-mobile-bar,.admin-sidebar,.admin-teams-heading,.admin-team-toolbar,.admin-team-list")];if(!history.state?.fisTeamSheet)history.pushState({...history.state,fisTeamSheet:true},"",location.href);document.body.style.overflow="hidden";background.forEach(el=>{el.inert=true});const pop=()=>setSelected(null);const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();history.back();return}if(event.key==="Tab"&&panel.current){const elements=[...panel.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];const first=elements[0],last=elements.at(-1);if(first&&last&&event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(first&&last&&!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};addEventListener("popstate",pop);document.addEventListener("keydown",key);panel.current?.querySelector<HTMLElement>("button")?.focus();return()=>{document.body.style.overflow="";background.forEach(el=>{el.inert=false});scrollTo(0,y);removeEventListener("popstate",pop);document.removeEventListener("keydown",key);trigger.current?.focus({preventScroll:true})}},[phone,selected]);
 function open(team:AdminTeam,button:HTMLButtonElement){trigger.current=button;setSelected(team);setDraft(toDraft(team));setReason("");setNotice(null)}
 function close(){if(phone&&history.state?.fisTeamSheet)history.back();else setSelected(null)}
 function save(){if(!selected||!draft||errors.length)return;const prompt=consequences.length?`Confirm these consequential changes:\n\n${consequences.map(item=>`- ${item}`).join("\n")}`:`Save changes to ${selected.name}?`;if(!confirm(prompt))return;startTransition(async()=>{const result=await saveTeamProfile(selected,draft,reason);if(!result.ok){setNotice({kind:"error",text:result.message});return}setNotice({kind:"success",text:"Complete team profile saved."});await onChanged();setSelected(null)})}
 return <><header className="admin-results-heading admin-teams-heading"><div><p className="eyebrow">Teams</p><h2>Team management</h2><p>{edition?.season??"Current season"}</p></div><Link className="admin-back-link" href="/admin">Return to dashboard</Link></header>{notice&&<p className={`admin-action-message ${notice.kind}`} role="status">{notice.text}</p>}
 <div className="admin-team-toolbar"><div className="admin-night-tabs">{(["monday","wednesday"] as const).map(value=><button key={value} aria-pressed={night===value} onClick={()=>{setNight(value);setDivision(workspace.editions.find(item=>item.night===value)?.division??"A");setSelected(null)}}>{value} night</button>)}</div>{divisions.length>1&&<label>Division<select value={division} onChange={e=>setDivision(e.target.value)}>{divisions.map(value=><option key={value}>{value}</option>)}</select></label>}<label>Status<select value={status} onChange={e=>setStatus(e.target.value as TeamStatus|"all")}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="withdrawn">Withdrawn</option><option value="replaced">Replaced</option></select></label><label>Team search<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <p className="admin-team-count"><strong>{teams.length}</strong> team{teams.length===1?"":"s"} shown</p><section className="admin-team-list" aria-label="Teams">{teams.map(team=><button key={team.id} onClick={e=>open(team,e.currentTarget)}><TeamKit colour={team.kitColour??undefined}/><span><strong>{team.name}</strong><small>{team.status} · {team.preferences.length} preference{team.preferences.length===1?"":"s"}</small></span><em>{team.kitColour??"No colour"}</em></button>)}{!teams.length&&<p className="admin-empty">No teams match these filters.</p>}</section>
 {selected&&draft&&<aside ref={panel} role={phone?"dialog":undefined} aria-modal={phone||undefined} aria-labelledby="team-editor-title" className={`admin-team-panel${phone?" admin-team-sheet":""}`}><button className="admin-panel-close" onClick={close} aria-label="Close team editor"><X/></button><h3 id="team-editor-title">Edit team profile</h3><TeamEditor original={selected} draft={draft} setDraft={setDraft} editions={workspace.editions}/><TeamComparison original={selected} draft={draft} workspace={workspace}/>{consequences.length>0&&<div className="admin-team-warning"><strong>Confirmation required</strong>{consequences.map(item=><p key={item}>{item}</p>)}<label>Administrative reason<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Why is this consequential change required?"/></label></div>}{errors.length>0&&<div className="admin-team-errors" role="alert">{errors.map(error=><p key={error}>{error}</p>)}</div>}<div className="admin-team-actions"><button disabled={pending} onClick={()=>{setDraft(toDraft(selected));setReason("")}}>Reset Changes</button><button className="primary" disabled={pending||errors.length>0} aria-busy={pending} onClick={save}>{pending?"Saving...":"Save Team"}</button></div></aside>}</>;
}

function TeamEditor({original,draft,setDraft,editions}:{original:AdminTeam;draft:TeamDraft;setDraft(value:TeamDraft):void;editions:TeamsWorkspace["editions"]}){function preferences(value:TeamPreference[]){setDraft({...draft,preferences:value})}return <div className="admin-team-editor"><div className="admin-team-fields"><label>Team name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as TeamStatus})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="withdrawn">Withdrawn</option><option value="replaced">Replaced</option></select></label><label>Competition / division<select disabled={original.hasHistory} value={draft.competitionSeasonId} onChange={e=>setDraft({...draft,competitionSeasonId:e.target.value})}>{editions.map(edition=><option key={edition.id} value={edition.id}>{edition.label} · Division {edition.division}</option>)}</select><small>{original.hasHistory?"Locked because this team has historical fixtures or adjustments.":"Changing this moves the team to another competition season."}</small></label></div><fieldset className="admin-kit-picker"><legend>Kit colour</legend><div className="admin-kit-preview"><TeamKit colour={draft.kitColour||undefined}/><strong>{draft.kitColour||"No colour"}</strong></div><div className="admin-colour-presets">{presets.map(preset=><button type="button" key={preset.value} aria-label={`Use ${preset.name}`} aria-pressed={draft.kitColour.toUpperCase()===preset.value} style={{background:preset.value}} onClick={()=>setDraft({...draft,kitColour:preset.value})}/>)}</div><label>Custom colour<input type="color" value={/^#[0-9a-f]{6}$/i.test(draft.kitColour)?draft.kitColour:"#000000"} onChange={e=>setDraft({...draft,kitColour:e.target.value.toUpperCase()})}/></label><label>Hex value<input value={draft.kitColour} placeholder="#FFFFFF" onChange={e=>setDraft({...draft,kitColour:e.target.value})}/></label></fieldset><PreferenceEditor values={draft.preferences} onChange={preferences}/><label>Fixture preference note<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="Private scheduling context for administrators"/><small>Blank notes are removed rather than saved.</small></label></div>}
function PreferenceEditor({values,onChange}:{values:TeamPreference[];onChange(value:TeamPreference[]):void}){return <fieldset className="admin-preferences"><legend>Kick-off preferences</legend>{values.map((preference,index)=><div className={`admin-preference-row is-${preference.classification}`} key={preference.id??index}><label>Time<input type="time" value={preference.kickoffTime} onChange={e=>onChange(values.map((value,i)=>i===index?{...value,kickoffTime:e.target.value}:value))}/></label><label>Strength<select value={preference.classification} onChange={e=>onChange(values.map((value,i)=>i===index?{...value,classification:e.target.value as TeamPreference["classification"]}:value))}><option value="required">Required</option><option value="preferred">Preferred</option><option value="avoid">Avoid</option></select></label><button type="button" onClick={()=>onChange(values.filter((_,i)=>i!==index))}>Remove</button></div>)}{!values.length&&<p className="admin-empty">No kick-off preferences recorded.</p>}<button type="button" onClick={()=>onChange([...values,{kickoffTime:"19:00",classification:"preferred"}])}>Add Preference</button></fieldset>}
function TeamComparison({original,draft,workspace}:{original:AdminTeam;draft:TeamDraft;workspace:TeamsWorkspace}){const name=(id:string)=>{const edition=workspace.editions.find(item=>item.id===id);return edition?`${edition.label} · Division ${edition.division}`:id};const rows=[["Name",original.name,draft.name],["Status",original.status,draft.status],["Competition",name(original.competitionSeasonId),name(draft.competitionSeasonId)],["Kit",original.kitColour??"None",draft.kitColour||"None"],["Preferences",original.preferences.length,draft.preferences.length],["Note",original.note||"None",draft.note.trim()||"None"]];return <section className="admin-team-comparison" aria-label="Original and proposed values"><h4>Review changes</h4>{rows.map(([label,before,after])=><p className={String(before)!==String(after)?"changed":""} key={String(label)}><span>{label}</span><b>{before}</b><i>→</i><b>{after}</b></p>)}</section>}
