-- Generated by npm run season:import:generate. Read-only checks plus temporary data.
-- Run after current-season-import.sql. All temporary records are rolled back.
begin;

create temporary table _fis_expected_standings (
  competition_season_id uuid, legacy_id text, team_name text, played integer,
  wins integer, draws integer, losses integer, goals_for integer,
  goals_against integer, goal_difference integer, points integer, position bigint
) on commit drop;
insert into _fis_expected_standings values
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-wildcats', 'Wildcats', 24, 19, 0, 5, 162, 97, 65, 57, 1),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-ghazni-united', 'Ghazni United', 24, 17, 2, 5, 167, 110, 57, 53, 2),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-afg', 'AFG', 24, 15, 2, 7, 156, 123, 33, 47, 3),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-goldlink-up', 'Goldlink Up', 24, 13, 3, 8, 176, 151, 25, 42, 4),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-misfits', 'Misfits', 24, 12, 1, 11, 148, 121, 27, 37, 5),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-hunger-fc', 'Hunger FC', 24, 11, 3, 10, 136, 129, 7, 36, 6),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-hope', 'Hope', 24, 10, 6, 8, 116, 118, -2, 36, 7),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-hazara-united', 'Hazara United', 24, 7, 5, 12, 70, 92, -22, 26, 8),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-goal-diggers', 'Goal Diggers', 24, 7, 3, 14, 91, 109, -18, 24, 9),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-toss', 'Toss', 24, 7, 2, 15, 94, 126, -32, 23, 10),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-top-up-fc', 'Top Up FC', 24, 5, 4, 15, 67, 83, -16, 19, 11),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-moza-mama', 'Moza Mama', 24, 6, 1, 17, 121, 157, -36, 19, 12),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-blue-dragons', 'Blue Dragons', 24, 6, 0, 18, 94, 185, -91, 18, 13),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-salvos', 'Salvos', 24, 4, 5, 15, 89, 138, -49, 17, 14),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-declans-team', 'Declan''s Team', 24, 5, 1, 18, 16, 54, -38, 16, 15),
  ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'mon-bunyip', 'Bunyip', 24, 5, 0, 19, 21, 64, -43, 15, 16),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-afg', 'AFG', 26, 23, 1, 2, 206, 121, 85, 70, 1),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-ghazni-united', 'Ghazni United', 26, 21, 0, 5, 213, 110, 103, 63, 2),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-goldlink-up', 'Goldlink Up', 26, 17, 4, 5, 195, 153, 42, 55, 3),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-pops', 'Pops', 26, 17, 1, 8, 197, 148, 49, 52, 4),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-hazara-united', 'Hazara United', 26, 13, 5, 8, 130, 117, 13, 44, 5),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-wildcats', 'Wildcats', 27, 13, 2, 12, 184, 164, 20, 41, 6),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-moza-mama', 'Moza Mama', 26, 12, 4, 10, 142, 133, 9, 40, 7),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-misfits', 'Misfits', 26, 11, 4, 11, 190, 166, 24, 37, 8),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-toss', 'Toss', 26, 11, 1, 14, 128, 133, -5, 34, 9),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-ibiza', 'Ibiza', 26, 8, 4, 14, 129, 150, -21, 28, 10),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-umoja-stars', 'Umoja Stars', 26, 4, 7, 15, 102, 148, -46, 19, 11),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-dwell-fc', 'Dwell FC', 26, 4, 6, 16, 80, 145, -65, 18, 12),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-unathletico', 'Unathletico', 26, 5, 2, 19, 97, 173, -76, 17, 13),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-rinnai', 'Rinnai', 26, 4, 2, 20, 134, 217, -83, 14, 14),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-mts-fc', 'MTS FC', 26, 4, 0, 22, 41, 120, -79, 12, 15),
  ('e1db4456-0663-55d2-95a1-681d17163b91', 'wed-xaywan', 'Kuq E Zi', 26, 2, 1, 23, 18, 93, -75, 7, 16);

do $verify$
begin
  if (select count(*) from public.teams where competition_season_id = '8021a2bb-eb2b-55fe-9900-d3f50facf092') <> 18
    then raise exception 'Monday team count does not match source'; end if;
  if (select count(*) from public.teams where competition_season_id = 'e1db4456-0663-55d2-95a1-681d17163b91') <> 16
    then raise exception 'Wednesday team count does not match source'; end if;
  if (select count(*) from public.fixtures where competition_season_id = '8021a2bb-eb2b-55fe-9900-d3f50facf092' and stage = 'regular_season') <> 146
    then raise exception 'Monday fixture count does not match source'; end if;
  if (select count(*) from public.fixtures where competition_season_id = 'e1db4456-0663-55d2-95a1-681d17163b91' and stage = 'regular_season') <> 180
    then raise exception 'Wednesday fixture count does not match source'; end if;
  if (select count(*) from public.result_versions r join public.fixtures f on f.id = r.fixture_id where f.competition_season_id = '8021a2bb-eb2b-55fe-9900-d3f50facf092' and r.status = 'published') <> 146
    then raise exception 'Monday result count does not match source'; end if;
  if (select count(*) from public.result_versions r join public.fixtures f on f.id = r.fixture_id where f.competition_season_id = 'e1db4456-0663-55d2-95a1-681d17163b91' and r.status = 'published') <> 180
    then raise exception 'Wednesday result count does not match source'; end if;
  if (select count(*) from public.standing_adjustments where competition_season_id = '8021a2bb-eb2b-55fe-9900-d3f50facf092' and publication_state = 'published') <> 21
    then raise exception 'Monday adjustment count does not match source'; end if;
  if (select count(*) from public.standing_adjustments where competition_season_id = 'e1db4456-0663-55d2-95a1-681d17163b91' and publication_state = 'published') <> 17
    then raise exception 'Wednesday adjustment count does not match source'; end if;
  if exists (
    select 1 from public.fixtures f left join public.teams h on h.id = f.home_team_id and h.competition_season_id = f.competition_season_id
      left join public.teams a on a.id = f.away_team_id and a.competition_season_id = f.competition_season_id
    where f.competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
      and (h.id is null or a.id is null)
  ) then raise exception 'A fixture team reference is unresolved'; end if;
  if exists (
    select 1 from public.fixtures where competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
      and publication_state = 'published' group by competition_season_id, match_date, kickoff_time, court having count(*) > 1
  ) then raise exception 'Duplicate published court slot detected'; end if;
  if exists (
    select 1 from public.result_versions r join public.fixtures f on f.id = r.fixture_id
    where f.competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
      and r.status = 'published' group by r.fixture_id having count(*) > 1
  ) then raise exception 'More than one published result exists for a fixture'; end if;
  if exists (
    select 1 from public.fixtures where competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
      and stage <> 'regular_season'
  ) then raise exception 'Knockout or grading records were imported'; end if;
  if exists (
    select 1 from public.teams where competition_season_id = '8021a2bb-eb2b-55fe-9900-d3f50facf092' and legacy_id not like 'mon-%'
  ) or exists (
    select 1 from public.teams where competition_season_id = 'e1db4456-0663-55d2-95a1-681d17163b91' and legacy_id not like 'wed-%'
  ) then raise exception 'Monday and Wednesday team datasets are not separated'; end if;
  if not exists (
    select 1 from public.teams t join public.standings s on s.team_id = t.id and s.competition_season_id = t.competition_season_id
    where t.id = '5569a976-4601-54ee-ac2e-fe57fec6dd4a' and t.status = 'inactive' and t.standings_eligible
  ) then raise exception 'Inactive standings-eligible Dwell FC is missing from standings'; end if;
  if exists (
    (select s.competition_season_id, t.legacy_id, s.team_name, s.played, s.wins, s.draws, s.losses,
      s.goals_for, s.goals_against, s.goal_difference, s.points, s.position
     from public.standings s join public.teams t on t.id = s.team_id
     where s.competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
     except select * from _fis_expected_standings)
    union all
    (select * from _fis_expected_standings
     except select s.competition_season_id, t.legacy_id, s.team_name, s.played, s.wins, s.draws, s.losses,
      s.goals_for, s.goals_against, s.goal_difference, s.points, s.position
     from public.standings s join public.teams t on t.id = s.team_id)
  ) then raise exception 'Supabase standings do not match the published JSON standings'; end if;
end;
$verify$;

select c.name as competition, count(*) as teams
from public.teams t join public.competition_seasons cs on cs.id = t.competition_season_id
join public.competitions c on c.id = cs.competition_id
where t.competition_season_id in ('8021a2bb-eb2b-55fe-9900-d3f50facf092', 'e1db4456-0663-55d2-95a1-681d17163b91')
group by c.name order by c.name;

rollback;
