import PolicyPage from "@/components/PolicyPage";

export const metadata = { title: "Privacy Policy", description: "How Futsal Indoor Soccer collects and handles personal information." };
const sections = [
  { heading: "Who we are", paragraphs: ["Futsal Indoor Soccer operates adult futsal competitions, currently including Monday and Wednesday nights at Endeavour Hills Leisure Centre."] },
  { heading: "Information we collect", paragraphs: ["We may collect registration and enquiry details, team and player names, contact information, postcode, gender, competition preferences, team details, fixtures, results, tables, team availability and preferences, communications, and signed captain onboarding forms.", "The website administration system does not store transaction history, medical information or emergency contacts. Financial records and cashflow tracking remain in a separate spreadsheet or accounting process."] },
  { heading: "How we use information", paragraphs: ["We use information to respond to enquiries, assess registrations, organise competitions and fixtures, record and publish results and tables, administer team requirements, communicate operational updates, maintain competition records and improve FIS services."] },
  { heading: "Forms, storage and access", paragraphs: ["Online forms are processed by Web3Forms and delivered to FIS. League information may be stored in password-protected administration systems and restricted cloud storage. Access is limited to people who need it for their FIS role.", "Captain onboarding forms may be returned by email or signed physically, scanned and uploaded. These forms may be retained for seven years."] },
  { heading: "Google Analytics", paragraphs: ["FIS uses Google Analytics to understand how visitors find and use the website. Analytics may collect device information, approximate location, pages visited and interactions. You can restrict analytics through browser settings and Google’s available controls."] },
  { heading: "Sharing and overseas processing", paragraphs: ["FIS does not sell personal information. Information may be shared with form, email, hosting, analytics, cloud-storage and competition-administration providers where reasonably necessary. Some providers may process information outside Australia."] },
  { heading: "Retention", paragraphs: ["Information is kept only while reasonably useful for competition administration, safety, disputes, insurance or legal requirements. Historical fixtures, results and tables may be retained as part of the competition record."] },
  { heading: "Access, correction and complaints", paragraphs: ["Email contact@futsalindoorsoccer.com.au to request access to or correction of your personal information, or to raise a privacy complaint. FIS may need to verify your identity before acting on a request."] },
];
export default function PrivacyPage() { return <PolicyPage title="Privacy Policy" updated="23 September 2026" sections={sections} />; }
