export type SeasonLifecycle="draft"|"validated"|"activated"|"abandoned";
export type DraftCompetition={id:string;sourceCompetitionSeasonId:string|null;categoryId:string;categoryName:string;locationId:string;locationName:string;weekday:number;division:string;name:string;retained:boolean};
export type DraftPreference={kickoff_time:string;classification:"required"|"preferred"|"avoid"};
export type DraftTeam={id:string;draftCompetitionId:string;sourceTeamId:string;selected:boolean;name:string;status:string;standingsEligible:boolean;kitColour:string|null;copyPrivateProfile:boolean;fixtureNote:string;preferences:DraftPreference[];sourceFixtureNote:string;sourcePreferences:DraftPreference[]};
export type SeasonDraft={id:string;sourceSeasonId:string|null;name:string;startsOn:string;endsOn:string;status:SeasonLifecycle;version:number;competitions:DraftCompetition[];teams:DraftTeam[]};
export type SeasonSummary={id:string;name:string;startsOn:string;endsOn:string;lifecycle:"active"|"archived";competitions:Array<{name:string;weekday:number;division:string;teamCount:number}>};
export type SeasonsWorkspace={active:SeasonSummary[];archived:SeasonSummary[];drafts:SeasonDraft[];categories:Array<{id:string;name:string}>;locations:Array<{id:string;name:string}>};
export type SeasonCreateInput={name:string;startsOn:string;endsOn:string};
export type SeasonCreateField=keyof SeasonCreateInput;
export function validateSeasonCreateFields(input:SeasonCreateInput){const errors:Partial<Record<SeasonCreateField,string>>={};if(!input.name.trim())errors.name="Season name is required.";if(!input.startsOn)errors.startsOn="Start date is required.";if(!input.endsOn)errors.endsOn="End date is required.";else if(input.startsOn&&input.endsOn<=input.startsOn)errors.endsOn="End date must be after the start date.";return errors}
export function validateSeasonDates(name:string,start:string,end:string){const errors:string[]=[];if(!name.trim())errors.push("Season name is required.");if(!start)errors.push("Start date is required.");if(!end)errors.push("End date is required.");if(start&&end&&end<=start)errors.push("End date must follow the start date.");return errors}
export function validatePreferences(preferences:DraftPreference[]){const errors:string[]=[],times=new Set<string>();for(const preference of preferences){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(preference.kickoff_time))errors.push(`Invalid kick-off time: ${preference.kickoff_time||"blank"}.`);if(!["required","preferred","avoid"].includes(preference.classification))errors.push(`Unsupported preference strength: ${preference.classification}.`);if(times.has(preference.kickoff_time))errors.push(`Duplicate or conflicting preference at ${preference.kickoff_time}.`);times.add(preference.kickoff_time)}return errors}
export function validateDraft(draft:SeasonDraft){const errors=validateSeasonDates(draft.name,draft.startsOn,draft.endsOn),competitions=draft.competitions.filter(c=>c.retained);if(!competitions.length)errors.push("Keep at least one competition.");const keys=new Set<string>();for(const c of competitions){const key=`${c.categoryId}:${c.locationId}:${c.weekday}:${c.division.trim().toLowerCase()}`;if(keys.has(key))errors.push(`Duplicate competition structure: ${c.name}.`);keys.add(key)}for(const c of competitions){const names=new Set<string>();for(const t of draft.teams.filter(t=>t.selected&&t.draftCompetitionId===c.id)){const name=t.name.trim().toLowerCase();if(names.has(name))errors.push(`Duplicate team name in ${c.name}: ${t.name}.`);names.add(name);if(t.copyPrivateProfile)errors.push(...validatePreferences(t.preferences).map(error=>`${t.name}: ${error}`))}}return errors}
export const draftCounts=(draft:SeasonDraft)=>({competitions:draft.competitions.filter(c=>c.retained).length,teams:draft.teams.filter(t=>t.selected).length,preferences:draft.teams.filter(t=>t.selected&&t.copyPrivateProfile).reduce((n,t)=>n+t.preferences.length,0),notes:draft.teams.filter(t=>t.selected&&t.copyPrivateProfile&&t.fixtureNote.trim()).length});
