export type StandingDelta={played:number;wins:number;draws:number;losses:number;goalsFor:number;goalsAgainst:number;points:number};
export type StandingDeltaDraft=Record<keyof StandingDelta,string>;
export type AdminStanding={competitionSeasonId:string;teamId:string;teamName:string;kitColour:string|null;position:number;played:number;wins:number;draws:number;losses:number;goalsFor:number;goalsAgainst:number;goalDifference:number;points:number};
export type StandingAdjustment={id:string;competitionSeasonId:string;teamId:string;reason:string;state:"draft"|"pending_review"|"published";kind:"standard"|"correction"|"reversal";supersedesId:string|null;version:number;createdAt:string;delta:StandingDelta};
export const emptyDelta=():StandingDelta=>({played:0,wins:0,draws:0,losses:0,goalsFor:0,goalsAgainst:0,points:0});
export const deltaToDraft=(delta:StandingDelta):StandingDeltaDraft=>Object.fromEntries(Object.entries(delta).map(([key,value])=>[key,String(value)])) as StandingDeltaDraft;
export const isEditableSignedInteger=(value:string)=>/^-?\d*$/.test(value);
export function normalizeSignedInteger(value:string){if(!/^-?\d+$/.test(value))return null;const parsed=Number(value);if(!Number.isSafeInteger(parsed))return null;return parsed===0?"0":String(parsed)}
export function parseDeltaDraft(draft:StandingDeltaDraft):StandingDelta|null{const entries=Object.entries(draft).map(([key,value])=>{const normalized=normalizeSignedInteger(value);return normalized===null?null:[key,Number(normalized)]});if(entries.some(entry=>entry===null))return null;return Object.fromEntries(entries as [keyof StandingDelta,number][]) as StandingDelta}
export function validateAdjustment(delta:StandingDelta,reason:string){const errors:string[]=[];if(!Object.values(delta).some(Boolean))errors.push("At least one standing value must change.");if(!reason.trim())errors.push("A meaningful reason is required.");if(!Object.values(delta).every(Number.isInteger))errors.push("Adjustments must be whole numbers.");return errors}
export function projectStanding(row:AdminStanding,delta:StandingDelta):AdminStanding{return{...row,played:row.played+delta.played,wins:row.wins+delta.wins,draws:row.draws+delta.draws,losses:row.losses+delta.losses,goalsFor:row.goalsFor+delta.goalsFor,goalsAgainst:row.goalsAgainst+delta.goalsAgainst,goalDifference:row.goalDifference+delta.goalsFor-delta.goalsAgainst,points:row.points+delta.points}}
